---
# tasks file for monogodb
- name: Install MongoDB
  apt:
    name: mongodb
    state: present
- name: Start and Enable MongoDB
  service:
    name: mongodb
    state: started
    enable: yes
- name: Configure MongoDB to access outside connection
  lineinfile:
    path: /etc/mongodb.conf
    regexp: '^#?bind_ip=127.0.0.1'
    line: 'bind_ip=127.0.0.1'
  notify:
    - restart mongodb